name: TAB-Bridge
version: @version@
author: NEZNAMY
main: me.neznamy.tab.bridge.bukkit.BukkitBridge
api-version: 1.13
website: "https://github.com/NEZNAMY/TAB-Bridge"
softdepend: [PlaceholderAPI, Vault]
description: "Extends features when TAB is installed on BungeeCord"
folia-supported: true